### ISSUE TITLE
Last Updated Bug

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#126]
Related to #34 

The "Last Updated" field is not automatically updating as expected & no date is being rendered.

<img width="349" alt="Screen Shot 2019-07-17 at 1 29 01 PM" src="https://user-images.githubusercontent.com/1896496/61396978-e611d580-a896-11e9-90d6-026f568150ef.png">

**Comment by leezaweb** [comment]
I don't see this bug on the deployed site, the fix branch, or your homepage branch preview. Yet I also don't see any changes to the relevant files.

**Comment by jnschrag** [comment]
Closing this for now as I think this was an issue with my local branch.
