### ISSUE TITLE
Component: Breadcrumbs

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#17]
Create the "breadcrumbs" component that will be included in the site header.
![screen shot 2018-10-23 at 12 42 50 pm](https://user-images.githubusercontent.com/1896496/47376665-391c7a80-d6c1-11e8-8fc8-ec8a0eba0b4b.png)

- [ ] Collection Title
- [ ] Brief Type (only for Issue Briefs on single posts)
- [ ] Post Title (only on single posts)

**Comment by aleesteele** [comment]
I have a clarifying question to ask about the breadcrumbs. 
On archive pages, what should be listed? I'm confused as to what the past_breadcrumb would be in this case.
All Analysis / Analysis?
Home / All Analysis?

On individual posts, it would (obviously) be this:
Briefs / Tech Brief / Name
Briefs / Country Profile / Name
Analysis / Name
Authors / Name
Workshops / Post

**Comment by jnschrag** [comment]
@aleesteele Good questions

I think on the archive pages, you can put "Home / Archive Name", so:
Home / Analysis
Home / Information Briefs
Home / Workshops

Individual posts look good to me, although for Authors, I would actually link it to Analysis instead of Authors
