### ISSUE TITLE
Component: Content Type

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#20]
Display the post's content type.
On individual posts:
![screen shot 2018-10-23 at 1 18 05 pm](https://user-images.githubusercontent.com/1896496/47378444-23f61a80-d6c6-11e8-8bd8-a126139672ca.png)

On post block:
![screen shot 2018-10-23 at 1 18 50 pm](https://user-images.githubusercontent.com/1896496/47378468-38d2ae00-d6c6-11e8-9151-a472e1fe9bbd.png)

- [x] Show the posts's collection
- [x] If the collection type is "briefs", show the "brief type"

**Comment by aleesteele** [comment]
Initial code base pushed (based off of HC), will edit when there is content.

**Comment by aleesteele** [comment]
Commenting on this: should the content type link to the respective algolia search? Should content type be displayed on other posts besides country profiles or tech primers? (ie analysis)

**Comment by jnschrag** [comment]
> Commenting on this: should the content type link to the respective algolia search? Should content type be displayed on other posts besides country profiles or tech primers? (ie analysis)
> 

For now, let's not make them a link, just static text. Yes, content type should be displayed for all posts. If you look at the #2 note on Zeplin screen "Single Post, HD" or look at the printed versions of the mockups, you'll see what it's supposed to be for types other than the issue briefs.
