### ISSUE TITLE
Component: Authors List

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#22]
Display a list of author names

- [x] Names should link to the author's page
- [x] List should be comma separate if more than 3 authors (eg. Jane Dot, John Doe, and Harry Potter)
- [x] Ultimate & penultimate names should be separate by "and" (eg. Jane Dot and John Doe)

**Comment by aleesteele** [comment]
Initial code base pushed (based off of HC), will edit when there is content.
