### ISSUE TITLE
Component: Categories List

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#28]
Display the list of categories related to the post.

- [ ] List of links to the search archive with the category specified in the URL, like so `/search/?dFR[keywords][0]=Ebola`

**Comment by jnschrag** [comment]
@aleesteele This was missed when doing the post details.

**Comment by aleesteele** [comment]
@jnschrag Woops, I must have missed that last month. On it!

**Comment by aleesteele** [comment]
@jnschrag Doublechecking this, though I also looked at #26. You meant the specific 'Categories' tag that are on Analysis posts, correct? Not all the subcategories (like 'Space', 'Air', etc. etc.)

Essentially this:
![screen shot 2019-01-10 at 4 10 36 pm](https://user-images.githubusercontent.com/18509789/50997477-ac7c9e00-14f2-11e9-8547-fa04910e4894.png)
Or this:
![screen shot 2019-01-10 at 4 11 08 pm](https://user-images.githubusercontent.com/18509789/50997485-b0102500-14f2-11e9-9034-676e0576375d.png)

**Comment by jnschrag** [comment]
@aleesteele That's a good question. I originally only meant the Categories, but since we do allow the user to filter according to the other results, it make sense that those would also be links as well.
