### ISSUE TITLE
Component: List of Keywords

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#30]
Display the list of keywords related to the post

- [x] List of links to the search archive with the keyword specified in the URL, like so `/search/?dFR[keywords][0]=Ebola`

**Comment by aleesteele** [comment]
Quick question on this as well @jnschrag: These are the keywords that display at the bottom of analysis posts, correct? On Zeplin they're on a sample "tech brief", which don't have keywords.
Silly, but figured I'd double check!
![screen shot 2018-11-13 at 4 13 46 pm](https://user-images.githubusercontent.com/18509789/48443426-1ed53a00-e75f-11e8-975f-0654dc2168cc.png)

**Comment by jnschrag** [comment]
@aleesteele Correct. Tucker only made one mockup for the single post type, but they only apply for the collection types that have tags, which I think is just posts/analysis.
