### ISSUE TITLE
Page: About

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#40]
- [ ] About the Project
- [ ] About PONI
- [ ] About the Nuclear Policy Working Group
- [ ] Principle Researchers
- [ ] Development Team

**Comment by aleesteele** [comment]
@jnschrag Should I go ahead and create the markdown and styling for this?
Note: Andrew Reddie and Bethany Goldblum aren't CSIS staff, and require headshots. Do these happen to be buried in an email somewhere?

Also, this is the language for the `Development Team` section, correct? (Taken from SOS): On the Radar is a product of the Andreas C. Dracopoulos iDeas Lab, the in-house digital, multimedia, and design agency at the Center for Strategic and International Studies.

**Comment by jnschrag** [comment]
@aleesteele Yes please!

No, I don't believe we have headshots for them. But we can certainly ask. For now, let's build it in such a way it can accommodate both situations (having and not having) a headshot.

**Comment by aleesteele** [comment]
@jnschrag Ok! The About page has all necessary information. The front matter template was also made on Forestry.

In the meantime, I've started to lay this out on here, adding the basic text styles (and without the pseudo-element lines & aside: https://github.com/CSIS-iLab/on-the-radar/tree/feature/about-page

Should this aside be made as an include?
![screen shot 2019-01-15 at 3 55 01 pm](https://user-images.githubusercontent.com/18509789/51211158-b5021980-18e2-11e9-9917-4e52f820071b.png)
